FROM alpine:latest as BUILD_BASE
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk --update add gcc build-base openssh git cmake python3-dev py3-pip libffi-dev boost-dev jsoncpp-dev yaml-cpp-dev librdkafka-dev bash bash-completion fish zsh zsh-autosuggestions nano curl protobuf-dev grpc-dev fmt-dev spdlog-dev curl-dev libgomp
RUN apk --update add glog-dev clang --repository=http://mirrors.tuna.tsinghua.edu.cn/alpine/edge/testing
# copy opencv2 libs
COPY --from=alpine/opencv:2.4.13 /opencv2/ /usr/
COPY --from=alpine/curlpp:latest /curlpp/ /usr/
WORKDIR /build/
ENTRYPOINT ["/bin/zsh"]
