FROM python:slim as BUILD_BASE
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ="Asia/Shanghai"
RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
RUN sed -i 's/security.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
RUN apt-get update && apt-get install -y libstdc++6
COPY --from=debian/curlpp:latest /curlpp/ /usr/
ENTRYPOINT ["/bin/bash"]
